// Core module - platform agnostic code
// This can be shared between React Web and React Native

// Types
export * from './types';

// Services
export {
  BaseService,
  DeviceService,
  SettingsService,
  NetBoxService,
  configureServices,
  getServiceConfig,
  getServices,
  getWebSocketService,
  WebSocketService,
  type ServiceConfig,
  type Services,
  type WebSocketEvent,
  type WebSocketEventType,
  type DeviceDiscoveredPayload,
  type WebSocketEventHandler,
  type ConnectResult,
  type ConfigResult,
  type BackupContentResult,
  type PingResult,
  type SSHResult,
  type NetBoxConfig,
  type NetBoxStatus,
  type NetBoxSyncResult,
  type NetBoxManufacturer,
  type NetBoxSite,
  type NetBoxDeviceRole,
  type NetBoxDevice,
  type DetectedVariable,
  type TemplatizeResponse,
} from './services';

// Hooks
export {
  useDevices,
  useSettings,
  useBackups,
  useVendors,
  useDhcpOptions,
  useTemplates,
  useDiscovery,
  useTestContainers,
  useTheme,
  useWebTheme,
  useForm,
  useWebSocket,
  useModalForm,
  useNotification,
  createMobileNotificationHandler,
  createWebNotificationHandler,
  useListFiltering,
  useAsyncModal,
  useSimpleModal,
  useLocalSettings,
  useLocalAddresses,
  getLocalApiUrl,
  setLocalApiUrl,
  THEME_OPTIONS,
  type UseDevicesOptions,
  type UseDevicesReturn,
  type UseSettingsReturn,
  type UseBackupsReturn,
  type UseVendorsOptions,
  type UseVendorsReturn,
  type UseDhcpOptionsOptions,
  type UseDhcpOptionsReturn,
  type UseTemplatesOptions,
  type UseTemplatesReturn,
  type UseDiscoveryOptions,
  type UseDiscoveryReturn,
  type UseTestContainersOptions,
  type UseTestContainersReturn,
  type ThemeConfig,
  type UseThemeOptions,
  type UseThemeReturn,
  type UseFormOptions,
  type UseFormReturn,
  type UseWebSocketOptions,
  type UseWebSocketReturn,
  type UseModalFormOptions,
  type UseModalFormReturn,
  type NotificationType,
  type NotificationMessage,
  type ConfirmOptions,
  type NotificationHandler,
  type UseNotificationOptions,
  type UseNotificationReturn,
  type UseListFilteringOptions,
  type UseListFilteringReturn,
  type GroupedItems,
  type UseAsyncModalOptions,
  type UseAsyncModalReturn,
  type LocalSettings,
  type UseLocalSettingsReturn,
  type UseLocalAddressesReturn,
} from './hooks';

// Utils
export {
  formatDate,
  formatRelativeTime,
  formatMacAddress,
  formatFileSize,
  formatExpiry,
  formatEventType,
  getEventTypeIcon,
  validateMacAddress,
  validateIpAddress,
  validateHostname,
  validateDeviceForm,
  validateSettingsForm,
  getErrorMessage,
  parseApiError,
  lookupVendorByMac,
  setVendorCache,
  getVendorCache,
  randomHex,
  generateMac,
  getVendorPrefixOptions,
  getVendorClassForVendor,
  getVendorFilterOptions,
  getVendorSelectOptions,
  getVendorName,
  groupByVendor,
  filterByVendor,
  generateId,
  slugify,
  createChangeHandler,
  parseListValue,
  formatListValue,
  getStatusColor,
  getStatusColors,
  getVariableTypeIcon,
  getVariableTypeColor,
  getStatusIcon,
  getStatusLabel,
  type ValidationResult,
  type ParsedApiError,
  type DiscoveryEventType,
  type VendorPrefixOption,
  type VendorFilterOption,
  type VendorSelectOption,
  type GroupedByVendor,
  type VariableTypeIcon,
  type StatusIcon,
} from './utils';

// Constants
export {
  DEFAULT_DHCP_OPTIONS,
  DHCP_OPTION_TYPES,
  EMPTY_VENDOR_FORM,
  EMPTY_DHCP_OPTION_FORM,
  EMPTY_TEMPLATE_FORM,
  SAMPLE_DEVICE_FOR_PREVIEW,
  VENDOR_CLASS_OPTIONS,
  CONFIG_METHOD_OPTIONS,
} from './constants';

// Theme
export {
  darkTheme,
  lightTheme,
  plainTheme,
  themes,
  getThemeColors,
  MONOSPACE_FONT,
  FONT_SIZES,
  type ThemeColors,
  type FontSize,
} from './theme';
